fork = false
frame = "buttonless"
idle = true
maximized = false
no-multigrid = true
neovim-bin = '/opt/homebrew/bin/nvim'
theme = "auto"
srgb = false
tabs = false
title-hidden = true
vsync = false
wsl = false

[font]
size = 14
hinting = "full"
normal = ["JetBrainsMono Nerd Font Propo"]
