fork = false
frame = "buttonless"
idle = true
maximized = false
no-multigrid = false
neovim-bin = '/opt/homebrew/bin/nvim'
srgb = false
tabs = false
title-hidden = true
vsync = false
wsl = false

[font]
size = 16
hinting = "full"

[[font.normal]]
family = "ZedMono Nerd Font"
style = "Extended"

