fork = false
frame = "buttonless"
idle = true
maximized = false
no-multigrid = false
neovim-bin = '/opt/homebrew/bin/nvim'
srgb = false
tabs = false
title-hidden = true
vsync = false
wsl = false

[font]
normal = ["GeistMono Nerd Font"]
size = 14


