# Configuration for Alacritty, the GPU enhanced terminal emulator
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.75
# startup_mode="SimpleFullScreen"
blur = true
decorations = "ButtonLess"
padding = { x = 8, y = 8  }
resize_increments = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 14

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux new-session -A -s main"]
