# Configuration for Alacritty, the GPU enhanced terminal emulator
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
blur = true
decorations = "ButtonLess"
resize_increments = true
option_as_alt = "OnlyLeft"
# padding = { x = 3 , y = 2  } # 1440p display
padding = { x = 5 , y = 7  } # macbook pro display

[font]
normal = { family = "JetBrainsMono Nerd Font Propo"}
# normal = { family = "ZedMono Nerd Font", style = "Extended" }
# bold = { family = "ZedMono Nerd Font", style = "Extended Bold"}
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
offset.x = 0
offset.y = 4
# size = 16 # 1440p display
size = 14 # macbook pro display

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux new-session -A -s main"]
