# Configuration for Alacritty, the GPU enhanced terminal emulator
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
startup_mode="SimpleFullScreen"
blur = true
decorations = "ButtonLess"
padding = { x = 5 , y = 9  }
resize_increments = true
option_as_alt = "OnlyLeft"

[font]
normal = { family = "ZedMono Nerd Font", style = "Extended" }
bold = { family = "ZedMono Nerd Font", style = "Extended Bold"}
offset.x = 1  # For letter spacing (default: 0)
offset.y = 2  # For line spacing (default: 0)
size = 14

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux new-session -A -s main"]
